#!/usr/bin/env bash

OPTIND=1
while getopts :cu option
do
    case "$option" in
        c ) rm -rf tmp;; # clean
        u ) # uninstall
            rm -rf tmp/all
            find tmp/pkg -type f -name token-make-install -delete;;
        '?' ) printf "Unknown short option \"%s\"" "$OPTARG"; exit 1;;
        : ) printf "Short option \"%s\" missing argument" "$OPTARG"; exit 1;;
    esac
done
shift $((OPTIND-1))

make -f configure.mk
PATH=/bin:/usr/bin:/opt/local/bin ./configure --prefix=$PWD/tmp/root
make "$@"

